services:
  - type: web
    name: gshptc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gshptc-db
          property: connectionString

databases:
  - name: gshptc-db
    databaseName: gshptc
    plan: free
    ipAllowList: []
